public class UpdateAccountController {

    public String Page {get; set;}
    public String OpenPageURL {get; set;}
    
    public void QuoteToExcelClass()
    {
        Page = '' ;
        OpenPageURL = '' ;
    }
    
   /* public PageReference redirect()
    {
            //OpenPageURL = '<a target="_blank" href="http://www.google.co.in/ rel="nofollow">http://www.google.co.in/'</a>' ;
            //OpenPageURL = '<a target="_blank" href="http://www.google.co.in/'" rel="nofollow">http://www.google.co.in/'</a> ;
            //OpenPageURL = '<a target="test" href="https://ibirdssoftwarepvtltd-dev-ed.lightning.force.com/"</a>' ;
            OpenPageURL = '<a href="https://ibirdssoftwarepvtltd-dev-ed.my.salesforce.com/"</a>' ;
        return null;
    }*/

}